# Generated by Django 4.2.1 on 2023-09-27 16:23

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد ')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_image/')),
                ('job', models.CharField(blank=True, max_length=120, null=True, verbose_name=' شغل ')),
                ('phone', models.CharField(max_length=11)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=120, verbose_name='پیام')),
                ('name', models.CharField(max_length=250, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('active', models.BooleanField(default=False, verbose_name='وضعیت')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('کلاه', 'کلاه'), ('عینک', 'عینک'), ('وسایل خانه', 'وسایل خانه')], default='کلاه', max_length=12)),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('slug', models.SlugField(max_length=250, verbose_name='اسلاگ')),
                ('price', models.CharField(max_length=20, verbose_name='قیمت')),
                ('publish', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published'), ('RJ', 'Rejected')], default='DF', max_length=2, verbose_name='وضعیت')),
                ('reading_time', models.PositiveIntegerField(verbose_name='زمان مطالعه')),
                ('old_price', models.CharField(default='', max_length=12)),
                ('discount', models.CharField(default='', max_length=12)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصول ها',
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[500, 500], upload_to='post_images/')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='توضیحات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productmodel')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'عکس ها',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250, verbose_name='عنوان نظر')),
                ('message_positive_points', models.TextField(default='', max_length=250, verbose_name=' نکات مثبت')),
                ('message_negative_points', models.TextField(default='', max_length=250, verbose_name=' نکات منفی')),
                ('message_text', models.TextField(default='', max_length=250, verbose_name=' متن پیام ')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('email', models.EmailField(default='', max_length=250, verbose_name='ایمیل')),
                ('phone', models.TextField(default='', max_length=250, verbose_name=' تلفن')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.productmodel')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
                'ordering': ['created'],
            },
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['-publish'], name='products_pr_publish_0290a4_idx'),
        ),
        migrations.AddIndex(
            model_name='imagemodel',
            index=models.Index(fields=['-title'], name='products_im_title_1d4fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='commentmodel',
            index=models.Index(fields=['created'], name='products_co_created_791b2f_idx'),
        ),
    ]
