# Generated by Django 4.2.4 on 2023-08-03 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_imagemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'ordering': ['-title'], 'verbose_name': 'عکس', 'verbose_name_plural': 'عکس ها'},
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productmodel'),
        ),
        migrations.AddIndex(
            model_name='imagemodel',
            index=models.Index(fields=['-title'], name='products_im_title_1d4fdf_idx'),
        ),
    ]
