# Generated by Django 4.2.1 on 2023-10-24 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_productmodel_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="like_products", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
