# Generated by Django 4.2.4 on 2023-08-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_imagemodel_options_alter_imagemodel_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
