# Generated by Django 4.2.1 on 2023-12-03 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_productmodel_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="saved_by",
            field=models.ManyToManyField(
                related_name="saved_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
