# Generated by Django 4.2.1 on 2023-12-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_productmodel_saved_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="category",
            field=models.CharField(
                choices=[
                    ("موبایل", "موبایل"),
                    ("عینک", "عینک"),
                    ("وسایل خانه", "وسایل خانه"),
                    ("کالای دیجیتال", "کالای دیجیتال"),
                ],
                default="موبایل",
                max_length=39,
            ),
        ),
    ]
