# Generated by Django 4.2.4 on 2023-08-12 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_commentmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'راه ارتباطی'},
        ),
    ]
