# Generated by Django 4.2.4 on 2023-08-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_contactmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'راه ارتباطی', 'verbose_name_plural': 'راه های ارتباطی'},
        ),
    ]
