# Generated by Django 4.2.4 on 2023-08-19 02:18

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_contactmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
