# Generated by Django 4.2.4 on 2023-08-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_imagemodel_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'ordering': (['name'],)},
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='email',
            field=models.EmailField(default='ff', max_length=250, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='message',
            field=models.TextField(default='ff', max_length=250, verbose_name='متن کامنت'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='phone',
            field=models.TextField(default='ff', max_length=250, verbose_name=' تلفن'),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='active',
            field=models.BooleanField(default=False, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='body',
            field=models.TextField(default='ff', max_length=250, verbose_name='متن کامنت'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='name',
            field=models.CharField(default='ff', max_length=250, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.CharField(max_length=120, verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='subject',
            field=models.CharField(choices=[('پیشنهاد', 'پیشنهاد'), ('انتقاد', 'انتقاد'), ('گزارش', 'گزارش')]),
        ),
        migrations.AddIndex(
            model_name='contactmodel',
            index=models.Index(fields=['name'], name='products_co_name_efac0a_idx'),
        ),
    ]
