# Generated by Django 4.2.4 on 2023-08-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_contactmodel_options_commentmodel_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='body',
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='message',
            field=models.TextField(default='ff', max_length=250, verbose_name='متن '),
        ),
    ]
