# Generated by Django 4.2.4 on 2023-08-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_commentmodel_body_alter_commentmodel_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='email',
            field=models.EmailField(default='your email', max_length=250, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='message',
            field=models.TextField(default='text', max_length=250, verbose_name='متن '),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='name',
            field=models.CharField(default='your name', max_length=250, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='phone',
            field=models.TextField(default='your phone', max_length=250, verbose_name=' تلفن'),
        ),
    ]
