# Generated by Django 4.2.1 on 2023-08-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_commentmodel_email_alter_commentmodel_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='discount',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='old_price',
            field=models.CharField(default='', max_length=12),
        ),
    ]
