# Generated by Django 4.2.1 on 2023-08-29 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_commentmodel_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='message',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='subject',
        ),
    ]
