# Generated by Django 4.2.1 on 2023-08-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_rename_message_contactmodel_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='contactmodel',
            name='products_co_name_efac0a_idx',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='email',
            field=models.EmailField(default='', max_length=20, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='شماره موبایل'),
        ),
    ]
