# Generated by Django 4.2.1 on 2023-09-01 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_commentmodel_created_alter_imagemodel_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='name',
        ),
    ]
